# Generated by Django 3.0.6 on 2021-09-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
