# Generated by Django 3.0.6 on 2021-09-24 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210924_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuyproduct',
            name='Price_Final',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userbuyproduct',
            name='user_buy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
