# Generated by Django 3.2.7 on 2021-09-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210921_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='<None>', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
