# Generated by Django 3.2.8 on 2021-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20211012_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
